### PR TITLE
Correct logic to handle legacy V1 keys

### PR DESCRIPTION
**Pull request by kn2tod**
Just in case anyone is still trying to use the legacy V1 API keys, correct variable assignment so program logic can work smoothly.

### CODE REVIEW

**Comment by MW0MWZ** [comment]
BM call the V1 API, V1.0, the code checks later for greater or equal to 2 - why change this?

**Comment by MW0MWZ** [comment]
I should also have said, they call API v2.0, "2.0" and not "2"

**Comment by kn2tod** [comment]
Because, as discussed in <https://forum.pistar.uk/viewtopic.php?t=2878&start=10>, floating point numbers do not compute: 

if [[ ${APIVer} -ge 2 ]]; then

/usr/local/sbin/pistar-bmapi: line 108: [[: 1.0: syntax error: invalid arithmetic operator (error token is ".0")

**Comment by kn2tod** [comment]
I should also say: you're checking generally, generically for V1 or V2, not for 2.0 vs 2.1 or 1.3, so why use the ".0". It seems the distinction between V1 and V2 is the key lengths and not actually whether they are 1.x or 2.x.

**Comment by MW0MWZ** [comment]
linking the post is really handy - thank you.

**Pull request merged**
