### PR TITLE
Add support for flashing 12.288MHz MMDVM_HS_Hats

### PR DESCRIPTION
**Pull request by phl0**
The latest batch of MMDVM_HS_Hats was supplied with a 12.288MHz TCXO. That was added to the MMDVM_HS firmware scripts with https://github.com/juribeparada/MMDVM_HS/commit/62f34d8f6818e1d19a29d275e37aa7bc8dd1e82f.
This PR is to integrate that into PiStar.

### CODE REVIEW

**Comment by AndyTaylorTweet** [comment]
Thank you Flo, looks fine, just make sure customers know if they have the 12.288MHz version :)

**Comment by phl0** [comment]
Sure. We informed the guxy who bought from us. I will try and see if we can integrate the TCXO information into the version string of the firmware. Think this would help.

**Comment by AndyTaylorTweet** [comment]
Agreed, although I do output the string from MMDVMHost's log before flashing, we don't use that as a sanity check yet, although in this case that would be a good idea, since I/we could then output some message if you attempt to flash the board with the wrong firmware.

**Comment by phl0** [comment]
True. Let's see what we can do :)

**Pull request merged**
