### PR TITLE
pistar-upnp.service fix/improvement

### PR DESCRIPTION
**Pull request by narspt**
- ~fix pistar-upnp.service stop~ (now fixed by https://github.com/AndyTaylorTweet/Pi-Star_Binaries_sbin/pull/41)

- send upnp requests sequentially, one at a time, instead of all at once 

more details on commit comments...

### CODE REVIEW

**Comment by AndyTaylorTweet** [comment]
This one is a little bit painful, due to the fact that the dashboard can modify this file, if I update it - the updates may break on the client.

I'll have to modify the update process to force this change to over-write the local changes and take the update.

**Comment by narspt** [comment]
I thought about it... but thought that the 'update-index --assume-unchanged' you do on the update script would take care of that... but maybe I'm wrong - I didn't test it... but I'm sure you will find the best way :)

**Comment by narspt** [comment]
I see that the "pistar-upnp.service stop" issue is now fixed by https://github.com/AndyTaylorTweet/Pi-Star_Binaries_sbin/pull/41 then I did just update this PR to avoid conflict... for the case you ever want to merge my other suggestion...

**Comment by AndyTaylorTweet** [comment]
Your other suggestion was to add the trailing "&", that is present in this version - if i missed the very obvious, please make sure to tell me :)

**Comment by AndyTaylorTweet** [comment]
Gah OK, read the commit backwards - you wanted to remove the trailing "&" - OK got it..

**Comment by narspt** [comment]
Yes, remove them from each upnpc call so that they don't run all background at same time but run them all on a subshell in background to don't hang the script but allow running them sequentially, it's explained on the commit comments :)
Btw, I did update this to resolve conflicts some minutes ago :)

**Comment by narspt** [comment]
Thank you ;)

**Pull request closed without merging**
