### PR TITLE
RPT_Hat Flash Script

### PR DESCRIPTION
**Pull request by phl0**
This adds a script that can be used to update / flash the firmware for MMDVM_RPT_Hat boards by @mathisschmieder and @phl0 :-)

### CODE REVIEW

**Comment by AndyTaylorTweet** [comment]
Looks good, thank you.

**Comment by phl0** [comment]
Whow. That was fast :) Thank you

**Comment by AndyTaylorTweet** [comment]
I know I can trust your work 👍

**Comment by phl0** [comment]
> I know I can trust your work +1

Eeehhrrr well ..... I am also able to burn the whole thing down.... :-)

**Comment by AndyTaylorTweet** [comment]
I *did* read it first :) so you're good...

**Comment by phl0** [comment]
Alright then. Mni tnx and keep up the good work :)

**Pull request merged**
