### PR TITLE
Add support for flashing 12Mhz MMDVM_HS_Dual_Hats

### PR DESCRIPTION
**Pull request by phl0**

### CODE REVIEW

**Comment by AndyTaylorTweet** [comment]
Thank you

**Comment by AndyTaylorTweet** [comment]
Just a note here the script doesnt exist (in the releases section) so this wont work yet.

**Comment by phl0** [comment]
There will be soon :-)
https://github.com/juribeparada/MMDVM_HS/pull/50

**Comment by AndyTaylorTweet** [comment]
Excellent, just wanted to make sure :)

**Pull request merged**
