### PR TITLE
Fix filesystem in RW after boot. Bump to RC4.

### PR DESCRIPTION
**Pull request by f1rmb**

### CODE REVIEW

**Comment by AndyTaylorTweet** [comment]
There is little need to do this, there is an hourly cron job that also makes the disk RO, I can add it sure, but there is little benefit.

**Comment by f1rmb** [comment]
Hi,

   I know this isn't really critical, since there is no FS write access normally, but that was bugging me on a PI3 B+ runnng 4.0 RC3.
Also, some weeks ago, a Ham friend of mine even reinstalled everything on one of his hostpots, because of this (which is useless, i agree)

Cheers.

**Comment by AndyTaylorTweet** [comment]
OK tell you what - I will add this - when we bump out of RC and into the release - there are one or two things I want to do at the same time, so I will use this code then if that is OK with you ?

**Comment by f1rmb** [comment]
Yeah, sure that's fine with me.

Cheers.

**Pull request closed without merging**
