### PR TITLE
Improve XLX override

### PR DESCRIPTION
**Pull request by narspt**
Existing XLX override code would only allow to override default "room", this patch improves it to allow to override XLX ip (if specified*) or to add a completely new XLX host.

\* i.e. to override just the default "room", user should add on the override file something like:
012;;4022
or to override ip also:
012;194.38.140.205;4022

### CODE REVIEW

**Comment by AndyTaylorTweet** [comment]
Not so sure about this one, do we actually want the IP's to be over-ridden, since these are updated daily as part of the update process?

If I am missing the point here, please tell me :)

**Comment by narspt** [comment]
Well, all lists (DPlus, DExtra, DCS, ...) are updated daily... but in some cases we may want to override them for some reason... for example with the 012 in the example above, it's a real case for me, actually I override it to the Portuguese DCS012 server ip (now running a XLX daemon), because the official XLX012 in the list is another one... I guess there are many of these cases, as you surely know at least lower DCS and XRF numbering doesn't match, then when they migrate to XLX only one will be the "official" XLX one, and user may want to manually override it, you see what I mean...

Btw, as I did mention above, my code will still allow the current behavior of overriding just "room" if user doesn't specify the ip on the override file - what IMO makes sense anyway - why user will specify an ip on the override file that will be ignored? :)

**Comment by ct1jib** [comment]
Can do the same editing XLXHost.txt and add the changes on /root, this will override the system XLXHosts, but ok. 
But what will happen to the guys of Western ARC?

**Comment by narspt** [comment]
Jorge: Yes, the idea is exactly to allow user to be able to override it at the /root/XLXHost.txt file - currently you can't do it - as current code only allows to override default "room" and will ignore the ip you set on that override file :)  And concerning your question, obviously users that choose to override it will not be able to connect to the official XLX...

**Comment by AndyTaylorTweet** [comment]
The XLX list comes from the http://xlxapi.rlx.lu/api.php?do=GetXLXDMRMaster list (directly from the XLX registry) and is *NOT* based on the DCS/XRF/REF lists.

So when you use an XLX with DMR - the number/IP should always be correct (against the XLX master list).

Why would your XLX show up with a different number?
Please understand that I am not denying your request to add these changes, I just want to understand why they are important :)

**Comment by ct1jib** [comment]
narspt: Yes, you're rigth!! my solution is only available for "new" systems, don´t override the old ones.
Sorry, my mistake don't get the full picture.

**Comment by ct1jib** [comment]
Andy: The problem comes when the XLX born! as multiprotocol system should never have been "allowed" to register numbers below 32, there were before 32 DCS's, now problem arises, the DCS012 was transformed into XLX012 and someone occupied that position. We did our best, stating that only DCS mode can be used. 
From what I saw the Western ARC did the same, only accept DPlus and XRF.

**Comment by AndyTaylorTweet** [comment]
If you need to be able to add hosts to the XLX list - we can certainly add code to make that simple, since I do believe we should be supporting that.

**Comment by AndyTaylorTweet** [comment]
I understand the XLX/DCS/REF/XRF overlap issue - we maintain our own host files for that reason, I've given up trusting any external source

**Comment by narspt** [comment]
> The XLX list comes from the http://xlxapi.rlx.lu/api.php?do=GetXLXDMRMaster list (directly from the XLX registry) and is NOT based on the DCS/XRF/REF lists.
> 
> So when you use an XLX with DMR - the number/IP should always be correct (against the XLX master list).
> 
> Why would your XLX show up with a different number?

I understand it. But as Jorge said, imagine (just an example) that XRF012 owners migrate to XLX, then DCS012 owners also migrate to XLX, etc... (ok, main purpose of each will be to serve different protocols, but...) actually all of them will be XLX012 servers... however only one of them will be "the official XLX012" listed at XLX registry, right? Why shouldn't advanced user be able to override it, on it's override file, to be able to use an "unofficial" one instead? Why all override files at /root are intended to allow to override ip's except the XLX one that ignores them?

> If you need to be able to add hosts to the XLX list - we can certainly add code to make that simple, since I do believe we should be supporting that.

The patch also allows adding new hosts from the override file ;)

Do you see any specific issue/disadvantage with the extended functionality added by the patch?

OFF-TOPIC: Concerning the official XLX012... I did mention it initially just as an example, but talking about it... actually it seems taken but not even used... look at it's dashboard http://52.26.161.5/... also comparing ip's with DCS012/XRF012/REF012 none of these seems actually related to XLX012?

**Comment by ct1jib** [comment]
Andrew, I know that is not your business, but for you know DCS012 start operation on 2012/04/30 with two dns's, Torsten dns and our personnal (dcs012.xreflector.net and dstarportugal.com), at  that time the XLX not exists, with the end of DCS's we assume the same DCS012 because have 30~40 users daily connected. As I told before, the problem was created by having allowed (Luc) the creation of XLX with the same number as the DCS's.

**Comment by K2DLS** [comment]
This would be a highly useful feature for me.  I want to override the IP of an XLX that I operate so that I can access it via private addressing behind a firewall.

**Comment by narspt** [comment]
I see now that IP override is already implemented on 37ecf79bc400dd45dd3e478f411cbc1e554106f7, and overriding just room doesn't make sense anymore, closing...

**Pull request closed without merging**
